// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDogcroDIb5-7n9FPRTtIaCGE408irRuAM',
    appId: '1:527986192266:web:784c565c1e05d2b016a273',
    messagingSenderId: '527986192266',
    projectId: 'task-7239e',
    authDomain: 'task-7239e.firebaseapp.com',
    storageBucket: 'task-7239e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFNL87gcyxPQwYmTBkeeHW2rZDkwgtc6A',
    appId: '1:527986192266:android:6b920b32097cd0f116a273',
    messagingSenderId: '527986192266',
    projectId: 'task-7239e',
    storageBucket: 'task-7239e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyxFNtjX_LsnELxRZyNOSqc0U1XnIJC7U',
    appId: '1:527986192266:ios:bf5ea24502cc08a416a273',
    messagingSenderId: '527986192266',
    projectId: 'task-7239e',
    storageBucket: 'task-7239e.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyxFNtjX_LsnELxRZyNOSqc0U1XnIJC7U',
    appId: '1:527986192266:ios:bf5ea24502cc08a416a273',
    messagingSenderId: '527986192266',
    projectId: 'task-7239e',
    storageBucket: 'task-7239e.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDogcroDIb5-7n9FPRTtIaCGE408irRuAM',
    appId: '1:527986192266:web:88e1882cd0b1305316a273',
    messagingSenderId: '527986192266',
    projectId: 'task-7239e',
    authDomain: 'task-7239e.firebaseapp.com',
    storageBucket: 'task-7239e.firebasestorage.app',
  );

}